export const FETCH_WORKFLOW_DETAILS_REQUEST =
  "WORKFLOW/FETCH_WORKFLOW_DETAILS_REQUEST";
export const FETCH_WORKFLOW_DETAILS_SUCCESS =
  "WORKFLOW/FETCH_WORKFLOW_DETAILS_SUCCESS";
export const FETCH_WORKFLOW_DETAILS_FAILURE =
  "WORKFLOW/FETCH_WORKFLOW_DETAILS_FAILURE";
export const SET_SEARCHBAR_DATA = "SEARCHBAR/SET_SEARCHBAR_DATA";
