export const FETCH_MY_REQUESTS_REQUEST =
  "MY_REQUESTS/FETCH_MY_REQUESTS_REQUEST";
export const FETCH_MY_REQUESTS_SUCCESS =
  "MY_REQUESTS/FETCH_MY_REQUESTS_SUCCESS";
export const FETCH_MY_REQUESTS_FAILURE =
  "MY_REQUESTS/FETCH_MY_REQUESTS_FAILURE";
export const SET_SEARCHBAR_DATA = "MY_REQUESTS/SET_SEARCHBAR_DATA";
