export const FETCH_TODOLIST_REQUEST = "TODO/FETCH_TODOLIST_REQUEST";
export const FETCH_TODOLIST_SUCCESS = "TODO/FETCH_TODOLIST_SUCCESS";
export const FETCH_TODOLIST_FAILURE = "TODO/FETCH_TODOLIST_FAILURE";
export const SET_SEARCHBAR_DATA = "TODO/SET_SEARCHBAR_DATA";
