export const FETCH_SUMMARY_REQUEST = "SUMMARY/FETCH_SUMMARY_REQUEST";
export const FETCH_SUMMARY_SUCCESS = "SUMMARY/FETCH_SUMMARY_SUCCESS";
export const FETCH_SUMMARY_FAILURE = "SUMMARY/FETCH_SUMMARY_FAILURE";
export const SET_SEARCHBAR_DATA = "SUMMARY/SET_SEARCHBAR_DATA";
