export const FETCH_QUERY_REQUEST = "SEARCHBAR/FETCH_QUERY_REQUEST";
export const FETCH_QUERY_SUCCESS = "SEARCHBAR/FETCH_QUERY_SUCCESS";
export const FETCH_QUERY_FAILURE = "SEARCHBAR/FETCH_QUERY_FAILURE";
export const FETCH_SUGGESTIONS_REQUEST = "SEARCHBAR/FETCH_SUGGESTIONS_REQUEST";
export const FETCH_SUGGESTIONS_SUCCESS = "SEARCHBAR/FETCH_SUGGESTIONS_SUCCESS";
export const FETCH_SUGGESTIONS_FAILURE = "SEARCHBAR/FETCH_SUGGESTIONS_FAILURE";
export const HIDE_RIGHT_SIDEBAR = "SEARCHBAR/HIDE_RIGHT_SIDEBAR";
export const SET_CHAT_DETAILS = "SEARCHBAR/SET_CHAT_DETAILS";
